name: deployment
on:
  push:
    branches:
      - 'master'

jobs:
  buildPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run ng build --prod

      - name: 'Wait for SSH'
        run: |
          while ! nc -w5 -z ${{ secrets.OCI_IP_TERCERA }} 22; do
                  sleep 5
                  echo "SSH not available..."
          done; echo "SSH ready!"

      - name: Compress directory
        run:  tar -czvf compress.tar.gz dist

      - name: 'Push compress'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_IP_TERCERA }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_PRIVATE_KEY_TERCERA  }}
          source: compress.tar.gz
          target: "app"

  updateFront:
    runs-on: ubuntu-latest
    needs: buildPush
    steps:
      - name: 'Extract directory and move'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_IP_TERCERA }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_PRIVATE_KEY_TERCERA }}
          script: |
            cd app
            tar -xvf compress.tar.gz
            cd dist
            sudo rsync -a website /var/www/ytarama